version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin #修改用户名
      - COUCHDB_PASSWORD=123456 #修改密码
    volumes:
        - ./dbdata:/opt/couchdb/data
